name: Release Build

on:
  push:
    tags:
      - '*.*.*'
      - 'SNAPSHOT'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: application/build/libs/app.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_docs:
    needs: build_and_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout documentation repository
      uses: actions/checkout@v4
      with:
        repository: burdeamit/hello-there-md
        token: ${{ secrets.UPDATE_TOKEN }}
        path: documentation
    - name: Update version in _config.yaml
      run: |
        sed -i "s/latest_release: .*/latest_release: ${GITHUB_REF#refs/tags/}/" documentation/_config.yaml
    - name: Commit and push    
      run: |
        git config --global user.name '${{ secrets.USER_NAME }}'
        git config --global user.email '${{ secrets.USER_EMAIL }}'
        git add .
        git commit -m "Update version to ${GITHUB_REF#refs/tags/}"
        git push
      working-directory: documentation